# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tokenomics CI - RND & VC [local node]

env:
  MULTISIG_PRIVATE_KEY: ${{ secrets.MULTISIG_PRIVATE_KEY }}
  PROXYADMIN_PRIVATE_KEY: ${{ secrets.PROXYADMIN_PRIVATE_KEY }}
  ALICE_PRIVATE_KEY: ${{ secrets.ALICE_PRIVATE_KEY }}
  BACKEND_PRIVATE_KEY: ${{ secrets.BACKEND_PRIVATE_KEY }}
  
  MAINNET_URL: ${{ secrets.MAINNET_URL }}
  RINKEBY_TESTNET_URL: ${{ secrets.RINKEBY_TESTNET_URL }}
  GOERLI_TESTNET_URL: ${{ secrets.GOERLI_TESTNET_URL }}
  ROPSTEN_TESTNET_URL: ${{ secrets.ROPSTEN_TESTNET_URL }}
  SEPOLIA_TESTNET_URL: ${{ secrets.SEPOLIA_TESTNET_URL }}
  
  MOONBEAM_URL: ${{ secrets.MOONBEAM_URL }}
  MOONBASE_URL: ${{ secrets.MOONBASE_URL }}
  
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  MOONSCAN_API_KEY: ${{ secrets.MOONSCAN_API_KEY }}
  
on:
  push:
    branches:
      - development
      - main

  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.2]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx hardhat --version
    - run: npx hardhat test
